services:
  n8n:
    build: .
    ports:
      - 5678:5678
    restart: always
    # Uncomment below line if using Langfuse within n8n
    # env_file:
    #   - .env-n8n
    environment:
      - N8N_LOG_LEVEL=debug
      - N8N_METRICS=true
