global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: n8n
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:5678

# TODO: test
# - job_name: langfuse
#   honor_timestamps: true
#   scrape_interval: 15s
#   scrape_timeout: 10s
#   metrics_path: /metrics
#   scheme: http
#   static_configs:
#   - targets:
#     - host.docker.internal:3001

# TODO: pg-langfuse

# TODO: test
# - job_name: qdrant
#   honor_timestamps: true
#   scrape_interval: 15s
#   scrape_timeout: 10s
#   metrics_path: /metrics
#   scheme: http
#   static_configs:
#   - targets:
#     - host.docker.internal:6333
#     - host.docker.internal:6334
#     - host.docker.internal:6335

# node exporter
- job_name: node
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:9100
